---
abstract: 'ZeroMQ-based event messaging system.'
author:
  - 'Mischa Spiegelmock <revmischa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ZeroMQ-PubSub
no_index:
  directory:
    - t
    - inc
requires:
  Any::Moose: 0
  Clone: 0
  JSON: 0
  MooseX::Event: 0
  Test::More: 0
  ZeroMQ: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/revmischa/zeromq-pubsub.git
version: 0.06
